### ISSUE TITLE
Simple moving average crossover backtest tutorial?

### ISSUE THREAD

**Issue by potholiday** [systematicinvestor/SIT#18]
I am new to SIT and want to use it for backtesting my strategy. I searched google for a simple tutorial of using SIT but find nothing. The only tutorial I found was from [Inovance ](https://inovancetech.com/backtesttutorialr.html) and [yours](https://systematicinvestor.wordpress.com/2013/07/30/stop-loss/)  but its really complicated and I have no idea how to perform a simple moving average crossover strategy with one stock microsoft(MSFT) close price using SIT and quantmod(I know this library). If possible can you write a tutorial for MA crossover strategy?

this is code I wrote
```
library(quantmod) 
ticker = 'MSFT'
symbol = getSymbols(ticker,from="1990-01-01",auto.assign=F)
prices=Cl(symbol)
sma.fast=SMA(prices, 5)
sma.slow=SMA(prices, 30)
buy = ifelse((sma.fast> sma.slow), 1, NA)
sell=ifelse((sma.fast< sma.slow), -1, NA)
```
How can I use above code with SIT's tools for backtesting?
Also I have installed SIT in R

but when I tried this
```
library(SIT)
plota.test()
```
its giving this

```
null device 
          1 
```
Why its giving this? is it a error?

**Comment by systematicinvestor** [comment]
please have a look at
http://systematicinvestor.github.io/Thinking-SIT
http://systematicinvestor.github.io/Thinking-SIT2

**Comment by potholiday** [comment]
Hey thanks for the prompt reply. I am trying [this code](http://systematicinvestor.github.io/Thinking-SIT). I am confused with this part **prices = data$prices**,**data$weight[] = NA,
data$weight[] = signal** . I rewrote my code.

```
library(SIT)
library(quantmod) 
ticker = 'MSFT'
symbol = getSymbols(ticker,from="1990-01-01",auto.assign=F)
fast = bt.apply.matrix(prices, SMA, 5)
slow = bt.apply.matrix(prices, SMA, 30)
signal = iif(fast > slow, 1, 0)
#*****************************************************************
# Code Strategies
#*****************************************************************
models = list()

symbol$weight[] = NA
symbol$weight[] = signal
models$strategy = bt.run.share(symbol, clean.signal=F, silent=T)
#*****************************************************************
# Create Report
#*****************************************************************
plotbt(models, plotX = T, log = 'y', LeftMargin = 3, main = NULL)
mtext('Cumulative Performance', side = 2, line = 1)

print(plotbt.strategy.sidebyside(models, make.plot=F, return.table=T))
```
