### ISSUE TITLE
Code in python

### ISSUE THREAD

**Issue by martinbouhier** [systematicinvestor/SIT#39]
Hi there,
Do you have the code in python?
I'm really interested in!
Let me know please!
Have a nice day

Martin

**Comment by DonV1to10** [comment]
No I dont have it
    Am Dienstag, 24. März 2020, 07:44:35 MEZ hat Martin Bouhier <notifications@github.com> Folgendes geschrieben:  
 
 


Hi there,
Do you have the code in python?
I'm really interested in!
Let me know please!
Have a nice day

Martin
